### PR TITLE
change port to 3000

### PR DESCRIPTION
**Pull request by nihclil**
何羿勤

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
ok.

**Comment by cwpeng** [comment]
You have to merge pull request after review approval.

**Comment by cwpeng** [comment]
You should merge pull request after review approval.

**Comment by nihclil** [comment]
老師我是羿勤，抱歉之前的作業part_0沒有先merge😥這是我這周的作業，請幫我檢查

http://34.225.182.0:3000/api/attraction/10
http://34.225.182.0:3000/api/attractions/?page=0
http://34.225.182.0:3000/api/attractions/?page=0&keyword=北投
http://34.225.182.0:3000/api/attractions/?page=0&keyword=台
http://34.225.182.0:3000/api/mrts

**Comment by cwpeng** [comment]
OK. Done.

**Pull request merged**
